language: java

jdk: oraclejdk8

addons:
  sonarcloud:
    organization: "lorenzobettini-github"
    # required for Sonarcloud access
    token:
      secure: $SONAR_TOKEN

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.sonar/cache'

install: true

script:
 - mvn -f example.parent/pom.xml clean verify -Pjacoco coveralls:report sonar:sonar
